import { NextResponse } from "next/server";
import { supabaseAdmin } from "@/lib/supabaseAdmin";
import { MercadoPagoConfig, Preference } from "mercadopago";

function getSiteUrl(req: Request) {
  let siteUrl = process.env.NEXT_PUBLIC_SITE_URL;
  if (!siteUrl) {
    const protocol = req.headers.get("x-forwarded-proto") || "http";
    const host = req.headers.get("host");
    siteUrl = `${protocol}://${host}`;
  }
  return siteUrl.replace(/\/$/, "");
}

export async function POST(req: Request) {
  try {
    const body = await req.json();

    // ⚠️ SEGURIDAD MÁXIMA: Ignoramos price y extraPrice del body para evitar fraude
    const { planId, planName, extraVideo, name, email, referralCode } = body;

    if (!planId || !name || !email) {
      return NextResponse.json(
        { error: "Faltan datos obligatorios (Plan, Nombre o Email)." },
        { status: 400 }
      );
    }

    // 1) Precio base: SIEMPRE desde la Base de Datos (Anti-Hackeo)
    const { data: plan, error: planErr } = await supabaseAdmin
      .from("plans")
      .select("*")
      .eq("code", planId)
      .single();

    if (planErr || !plan) {
      return NextResponse.json(
        { error: "No se pudo encontrar el plan en la base de datos." },
        { status: 404 }
      );
    }

    const basePrice = plan.price_ars != null ? Number(plan.price_ars) : Number(plan.price) || 0;

    if (basePrice <= 0) {
      return NextResponse.json(
        { error: "Precio inválido configurado en la base de datos." },
        { status: 400 }
      );
    }

    let finalPrice = basePrice;
    let appliedDiscount = false;
    let validReferralCode = "";

    // 🔥 REGLA DE NEGOCIO: ¿Es un Plan Élite? (Para saber si le damos código y aplica descuento)
    const isElitePlan = String(planId).toLowerCase().includes('elite') || 
                        String(planId).toLowerCase().includes('leyenda') || 
                        String(planId).toLowerCase().includes('vip');

    // 2) Descuento por código (SOLO SE APLICA SI ESTÁ COMPRANDO UN PLAN ÉLITE)
    if (referralCode && isElitePlan) {
      const cleanCode = String(referralCode).trim().toUpperCase();

      // Códigos Maestros del Coach
      const masterCodes: Record<string, number> = {
        TUJAGUE20: 20,
        VERANO15: 15,
      };

      if (masterCodes[cleanCode]) {
        // Aplica código maestro
        const discountPercentage = masterCodes[cleanCode];
        finalPrice = finalPrice - (finalPrice * (discountPercentage / 100));
        appliedDiscount = true;
      } else {
        // 🔥 FIX: Validamos contra un código de embajador real en la BD
        try {
          const { data: ambassador, error: ambError } = await supabaseAdmin
            .from("orders")
            .select("id")
            .eq("referral_code", cleanCode)
            .limit(1)
            .maybeSingle();

          if (ambassador && !ambError) {
            finalPrice = finalPrice - (finalPrice * 0.15); // 15% de descuento al prospecto
            appliedDiscount = true;
            validReferralCode = cleanCode; // Guardamos quién lo refirió para pagarle después
          }
        } catch (e) {
          console.error("Error validando código de embajador:", e);
          // Si falla la validación, simplemente no aplicamos descuento, pero dejamos seguir la compra
        }
      }
    }

    // 3) Extra video: SIEMPRE desde DB (upsell-video) - Se suma DESPUÉS del descuento principal
    if (extraVideo) {
      const { data: extraPlan, error: extraErr } = await supabaseAdmin
        .from("plans")
        .select("*")
        .eq("code", "upsell-video")
        .single();

      if (extraErr || !extraPlan) {
        return NextResponse.json(
          { error: "ExtraVideo activado pero falta el plan 'upsell-video' en la tabla plans." },
          { status: 404 }
        );
      }

      const extraPriceDb = extraPlan.price_ars != null ? Number(extraPlan.price_ars) : Number(extraPlan.price) || 0;

      if (extraPriceDb > 0) {
        finalPrice += extraPriceDb;
      }
    }

    // MercadoPago en ARS: requiere números enteros, sin decimales
    finalPrice = Math.round(finalPrice);

    if (finalPrice <= 0) {
      return NextResponse.json(
        { error: "El precio final quedó inválido (0 o negativo). Revisá descuentos/precios." },
        { status: 400 }
      );
    }

    // 4) Identificador único de la orden
    const orderId = `ORD-${Date.now()}`;

    // 5) Código referido del nuevo cliente y Contraseña Base
    const firstName = String(name).split(" ")[0].toUpperCase();
    
    // 🔥 REGLA DE NEGOCIO: Solo le inventamos código si compró Élite. Si es plan estático, guardamos NULL.
    let newPersonalCode = null;
    if (isElitePlan) {
        const randomNum = Math.floor(100 + Math.random() * 900);
        newPersonalCode = `${firstName}${randomNum}`;
    }
    
    // Generamos la contraseña acá, pero NO creamos el usuario todavía (lo hará el Webhook si paga)
    const autogeneratedPassword = `${firstName.toLowerCase()}${Math.floor(1000 + Math.random() * 9000)}!`;

    // 6) Insert orden PENDING en base de datos
    const planTitleToStore = plan.name || planName || planId;

    const { error: insertError } = await supabaseAdmin.from("orders").insert({
      order_id: orderId,
      user_id: null, // Se llena cuando el Webhook confirma el pago
      password: autogeneratedPassword, // La guardamos para que el Webhook se la envíe por email
      customer_name: name,
      customer_email: email,
      plan_id: planId,
      plan_title: planTitleToStore,
      amount_ars: finalPrice,
      status: "pending",
      payment_method: "mercadopago",
      has_video_review: !!extraVideo,
      referred_by: validReferralCode || null, // A quién hay que pagarle la comisión
      referral_code: newPersonalCode, // Su propio código de afiliado (Null si es plan estático)
      wallet_balance: 0,
    });

    if (insertError) {
      console.error("Error guardando orden en BD:", insertError);
      return NextResponse.json(
        { error: "Error al registrar la orden en la base de datos." },
        { status: 500 }
      );
    }

    // 7) Creación de Preferencia en MercadoPago
    const siteUrl = getSiteUrl(req);
    const client = new MercadoPagoConfig({ accessToken: process.env.MP_ACCESS_TOKEN! });
    const preference = new Preference(client);

    // 🔥 IMPORTANTE: Validamos que exista el token de MP
    if (!process.env.MP_ACCESS_TOKEN) {
        throw new Error("Falta configurar MP_ACCESS_TOKEN en las variables de entorno.");
    }

    const response = await preference.create({
      body: {
        items: [
          {
            id: planId,
            title: appliedDiscount ? `${planTitleToStore} (Con Descuento VIP)` : planTitleToStore,
            quantity: 1,
            unit_price: finalPrice,
            currency_id: "ARS",
          },
        ],
        external_reference: orderId,
        // 🔥 CORRECCIÓN: Ajustado al nombre real de tu carpeta (Webhooks con W mayúscula)
        notification_url: `${siteUrl}/api/Webhooks/mercadopago`,
        payer: { email, name },
        back_urls: {
          success: `${siteUrl}/exito`,
          failure: `${siteUrl}/?error=pago_rechazado`,
          pending: `${siteUrl}/exito`,
        },
        auto_return: "approved",
        // Habilitamos cuotas
        payment_methods: {
          installments: 3 
        }
      },
    });

    // Devolvemos el link de pago al Frontend para que redirija al usuario
    return NextResponse.json({ initPoint: response.init_point });

  } catch (error) {
    console.error("Error crítico en checkout:", error);
    return NextResponse.json({ error: "Error interno del servidor al procesar el pago." }, { status: 500 });
  }
}