import { NextResponse } from "next/server";
import { supabaseAdmin } from "@/lib/supabaseAdmin";
import { MercadoPagoConfig, Preference } from "mercadopago";

function getSiteUrl(req: Request) {
  let siteUrl = process.env.NEXT_PUBLIC_SITE_URL;
  if (!siteUrl) {
    const protocol = req.headers.get("x-forwarded-proto") || "http";
    const host = req.headers.get("host");
    siteUrl = `${protocol}://${host}`;
  }
  return siteUrl.replace(/\/$/, "");
}

export async function POST(req: Request) {
  try {
    const body = await req.json();

    // ⚠️ IGNORAMOS price y extraPrice del body para evitar fraude
    const { planId, planName, extraVideo, name, email, referralCode } = body;

    if (!planId || !name || !email) {
      return NextResponse.json(
        { error: "Faltan datos obligatorios (Plan, Nombre o Email)." },
        { status: 400 }
      );
    }

    // 1) Precio base: SIEMPRE desde DB
    const { data: plan, error: planErr } = await supabaseAdmin
      .from("plans")
      .select("*")
      .eq("code", planId)
      .single();

    if (planErr || !plan) {
      return NextResponse.json(
        { error: "No se pudo encontrar el plan en la base de datos." },
        { status: 404 }
      );
    }

    const basePrice = plan.price_ars != null ? Number(plan.price_ars) : Number(plan.price) || 0;

    if (basePrice <= 0) {
      return NextResponse.json(
        { error: "Precio inválido configurado en la base de datos." },
        { status: 400 }
      );
    }

    let finalPrice = basePrice;

    // 2) Extra video: SIEMPRE desde DB (upsell-video)
    if (extraVideo) {
      const { data: extraPlan, error: extraErr } = await supabaseAdmin
        .from("plans")
        .select("*")
        .eq("code", "upsell-video")
        .single();

      if (extraErr || !extraPlan) {
        return NextResponse.json(
          { error: "ExtraVideo activado pero falta el plan 'upsell-video' en la tabla plans." },
          { status: 404 }
        );
      }

      const extraPriceDb = extraPlan.price_ars != null ? Number(extraPlan.price_ars) : Number(extraPlan.price) || 0;

      if (extraPriceDb <= 0) {
        return NextResponse.json(
          { error: "Precio inválido configurado en DB para 'upsell-video'." },
          { status: 400 }
        );
      }

      finalPrice += extraPriceDb;
    }

    let appliedDiscount = false;
    let validReferralCode = "";

    // 3) Descuento por código (Master o Afiliado)
    if (referralCode) {
      const cleanCode = String(referralCode).trim().toUpperCase();

      const masterCodes: Record<string, number> = {
        TUJAGUE20: 20,
        VERANO15: 15,
      };

      if (masterCodes[cleanCode]) {
        const discountPercentage = masterCodes[cleanCode];
        finalPrice = finalPrice - finalPrice * (discountPercentage / 100);
        appliedDiscount = true;
      } else {
        const { data: ambassador } = await supabaseAdmin
          .from("orders")
          .select("id")
          .eq("referral_code", cleanCode)
          .single();

        if (ambassador) {
          finalPrice = finalPrice - finalPrice * 0.15;
          appliedDiscount = true;
          validReferralCode = cleanCode;
        }
      }
    }

    // MercadoPago en ARS: mejor cobrar entero
    finalPrice = Math.round(finalPrice);

    if (finalPrice <= 0) {
      return NextResponse.json(
        { error: "El precio final quedó inválido (0 o negativo). Revisá descuentos/precios." },
        { status: 400 }
      );
    }

    // 4) order_id único
    const orderId = `ORD-${Date.now()}`;

    // 5) código referido del nuevo cliente y Contraseña Base
    const firstName = String(name).split(" ")[0].toUpperCase();
    const randomNum = Math.floor(100 + Math.random() * 900);
    const newPersonalCode = `${firstName}${randomNum}`;
    
    // Generamos la contraseña acá, pero NO creamos el usuario todavía (lo hará el Webhook si paga)
    const autogeneratedPassword = `${firstName.toLowerCase()}${Math.floor(1000 + Math.random() * 9000)}!`;

    // 6) Insert orden PENDING
    const planTitleToStore = plan.name || planName || planId;

    const { error: insertError } = await supabaseAdmin.from("orders").insert({
      order_id: orderId,
      user_id: null, // Se llena cuando el Webhook confirma el pago
      password: autogeneratedPassword, // La guardamos para que el Webhook la use
      customer_name: name,
      customer_email: email,
      plan_id: planId,
      plan_title: planTitleToStore,
      amount_ars: finalPrice,
      status: "pending",
      payment_method: "mercadopago",
      has_video_review: !!extraVideo,
      referred_by: validReferralCode,
      referral_code: newPersonalCode,
      wallet_balance: 0,
    });

    if (insertError) {
      console.error("Error guardando orden en BD:", insertError);
      return NextResponse.json(
        { error: "Error al registrar la orden en la base de datos." },
        { status: 500 }
      );
    }

    // 7) Preferencia MP
    const siteUrl = getSiteUrl(req);
    const client = new MercadoPagoConfig({ accessToken: process.env.MP_ACCESS_TOKEN! });
    const preference = new Preference(client);

    const response = await preference.create({
      body: {
        items: [
          {
            id: planId,
            title: appliedDiscount ? `${planTitleToStore} (Con Descuento)` : planTitleToStore,
            quantity: 1,
            unit_price: finalPrice,
            currency_id: "ARS",
          },
        ],
        external_reference: orderId,
        // 🔥 CORRECCIÓN CRÍTICA: De "webhooks" a "webhook" (singular) para que coincida con tu carpeta 🔥
        notification_url: `${siteUrl}/api/webhook/mercadopago`,
        payer: { email, name },
        back_urls: {
          success: `${siteUrl}/exito`,
          failure: `${siteUrl}/?error=pago_rechazado`,
          pending: `${siteUrl}/exito`,
        },
        auto_return: "approved",
        payment_methods: {
          installments: 3 
        }
      },
    });

    return NextResponse.json({ initPoint: response.init_point });
  } catch (error) {
    console.error("Error en checkout:", error);
    return NextResponse.json({ error: "Error interno del servidor." }, { status: 500 });
  }
}